### ISSUE TITLE
Potential for this to be used with other Bethesda titles, i.e. Fallout 4, Fallout 3, Skyrim?

### ISSUE THREAD

**Issue by PerryTute** [TAN-Gaming/FalloutNV-No-Registry-Patch#1]
There are a few total conversions, such as Endreal and Fallout London that are a bit of a pain to switch from a vanilla install to said conversion, I'm only really familiar with python and have been thinking about having a crack, was just wondering how difficult this may be.

**Comment by TAN-Gaming** [comment]
I have never played those mods or conversions before so I can only answer from the technical point of view.

Basically, what the patch does is just hooking Windows APIs. You can inject the patch code (NoRegPatch.c) into any game by building the patch code as a DLL with any name and use any DLL injection method to inject it into the game process before the game starts.

The things to consider are DRMs, a proxy DLL to use (if needed), what registry keys the game uses and the values it is expected.
If the game is DRM-free then you can create a custom launcher and use `CreateProcess` + `WriteProcessMemory` Windows APIs to inject the patch DLL. But if the game has DRMs, you may have to use a proxy DLL instead.
Please note that API hooking or DLL injection could be considered cheating and could trigger a ban if you are using them with online games.

> I'm only really familiar with python

I'm not sure if there is a way in Python to do API hooking or DLL injection, but if there is a way then I think you can create a custom launcher using it.
However, I would recommend using C/C++ or other native-compiled languages for this kind of mods.

**Comment by PerryTute** [comment]
Thank you for the technical explanation, thankfully the titles for the total conversions (Skyrim and Fallout 4 respectively) are available as DRM-free products on GOG so that's one hurdle out of the way, this looks to be a good reason to start learning C++, thanks again for the breakdown.
